---
title: "nba_api_contnuous_lineups"
author: "Ethan Carpenter"
date: "8/3/2020"
output: html_document
---

```{r setup, include=FALSE}
source('nba_api.R')
source('tools.R')
source('element_gradient_setup.R')
source('game_flow.R')
library(dplyr)
library(zoo)
library(runner)
library(ggplot2)
library(RSQLite)
library(png)
library(teamcolors)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
id <- '0021901271'
dt <- get_continous_lineups(id, '2020-08-06')
player_codes <- get_pbp_data(id, '2020-08-06') %>%
    filter(str_detect(description, 'shot') |
             str_detect(description, 'Substitution') |
             str_detect(description, 'Rebound')) %>%
    select(person_id, player_code, team_abr) %>%
    distinct() %>%
    filter(str_detect(player_code, '_')) %>%
    mutate(player_code=map_chr(str_split(player_code, '_'), 2),
           player_code=tools::toTitleCase(player_code))
colors_master <- get_colors_master()

new_dt <- data.frame(player=character(),
                     in_game=numeric(),
                     n=numeric(),
                     person_id=character(),
                     team_abr=character(),
                     seconds=numeric())
team <- 'LAC'

player_codes %>% arrange(player_code) %>% filter(team_abr==team) %>% rmarkdown::paged_table(
)
```



```{r}
color <- colors_master %>%
  filter(Abbreviation==team) %>%
  select(primary_color) %>%
  unlist()
player_codes <- player_codes %>%
  filter(team_abr==team)
colnames(dt) <- map_chr(str_split(colnames(dt), ' '), 1)
colnames(dt) <- tools::toTitleCase(tolower(colnames(dt)))
dt <- dt[, colnames(dt) %in% player_codes$player_code]

for (i in 1:length(colnames(dt))){
  col <- colnames(dt)[[i]]
  
  player_info <- player_codes %>%
    filter(player_code==col) %>%
    select(person_id, team_abr) %>%
    distinct()
  if (length(player_info) > 1)
    player_info <- player_info[1, ]
  
  new_dt <- new_dt %>%
    rbind(data.frame(player=col,
                     in_game=dt[[col]],
                     n=i,
                     person_id=player_info$person_id,
                     team_abr=player_info$team_abr,
                     seconds=0:(nrow(dt)-1)))
}

plot_dt <- new_dt %>%
  drop_na() %>%
  filter(in_game==1,
         team_abr==team)
labels <- plot_dt %>% 
  arrange(n) %>%
  select(player) %>% 
  distinct() %>%
  unlist()

p <- ggplot(plot_dt) +
  geom_rect(aes(xmin=n-1,
                xmax=n,
                ymin=seconds,
                ymax=seconds+1),
            fill=color
            ) +
  theme(legend.position = 'none',
        panel.grid.major.x = element_blank(),
        plot.background = element_gradient('white', 'white')) +
  scale_y_continuous(breaks=1:4 * 720, labels=c('End Q1', 'End Q2', 'End Q3', 'End Q4')) +
  scale_x_continuous(labels=labels,
                     breaks=1:length(labels) - 0.5)

for (i in 1:max(plot_dt$n)){
  player_code <- plot_dt %>%
    filter(n==i) %>%
    select(person_id) %>%
    distinct() %>%
    unlist()
  
  if (length(player_code) > 0)
    p <- p +
      annotation_raster(get_player_headshot(player_code),
                        i-1, i,
                        0, 400
                        )
}
#new_dt %>% rmarkdown::paged_table()
p
ggsave(paste0(team, id,'substitution_plots/sample_player_plot.png'))
```
```{r}
sec_dt <- plot_dt %>%
  group_by(seconds) %>%
  summarize(n=sum(in_game)) %>%
  arrange(-n)
max(sec_dt$n)
min(sec_dt$n)
pbp_dt %>%
  rmarkdown::paged_table()

ggplot(sec_dt, aes(y=n, x=seconds)) +
  theme(plot.background = element_gradient()) +
  geom_line() +
  scale_x_continuous(breaks=seq(1, 4)*12*60, labels=c('1Q', '2q', '3q', '4q'))
```
```{r}
pbp_dt %>%
  filter(team_abr=='NOP') %>%
  filter(EnterPlayer == 'Melli' | ExitPlayer == 'Melli')
```

